### ISSUE TITLE
Spec: Assignment YAML file format.

### ISSUE THREAD

**Issue by meling** [autograde/aguis#35]
The current format looks like this:

```yaml
AssignmentID: 2
Name: "Lab1"
Language: "Java"
Deadline: "27-08-2018 12:00"
AutoApprove: false
```

Question: Why do we need `Language` ? Perhaps what we actually need is a Docker image name.
